# Copyright (c) ModelScope Contributors. All rights reserved.
import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from ..base import Template
from ..constant import MLLMTemplateType
from ..register import TemplateMeta, register_template
from ..template_inputs import StdTemplateInputs
from ..utils import Context, Prompt, findall


class MuseGlimmerTemplate(Template):
    # `<|patch|>` / `<|video|>` are single placeholders in the rendered text; the processor expands
    # them into a start/end-wrapped patch run (videos additionally carry per-frame timestamps).
    image_token_id = 200092
    video_token_id = 200091
    placeholder_tokens = ['<|patch|>', '<|video|>']
    support_padding_free = False

    # Mirrors the `knowledge_cutoff` / `reasoning_strength` defaults of chat_template.jinja.
    knowledge_cutoff = '2026-01-04'
    reasoning_strength = 'high'

    # The generation prompt ends at `<|start|>assistant`, so the model emits its own recipient marker:
    # ` to=user<|message|>` opens the final answer, while ` to=self<|message|>...<|eom|>` is a thinking
    # turn followed by `<|start|>assistant to=user<|message|>`. Those markers are protocol rather than
    # content, so the thinking turn is rewritten into `<think>` tags and the markers are dropped.
    thinking_pattern = re.compile(r'\s*to=self<\|message\|>(.*?)<\|eom\|>\s*<\|start\|>assistant(?=\s*to=)', re.DOTALL)
    marker_pattern = re.compile(r'\s*to=\w+<\|message\|>|<\|eom\|>|<\|start\|>assistant')

    def decode_generate_ids(self, generate_ids, **kwargs) -> Any:
        response = super().decode_generate_ids(generate_ids, **kwargs)
        if self.is_training or not isinstance(response, str):
            return response
        response = self.thinking_pattern.sub(lambda m: f'<think>{m.group(1)}</think>', response)
        # Streaming hands out increments, so a thinking turn split across chunks cannot be matched as a
        # whole; dropping the bare markers at least keeps the protocol out of the user-visible text.
        return self.marker_pattern.sub('', response)

    def _get_system_suffix(self) -> str:
        # The jinja template appends the reasoning hint and the recipient list to every system
        # message. Tool schemas, when supported, are inserted between the two.
        return (f'\n\nReasoning strength: {self.reasoning_strength}.'
                '\n\n# Valid recipients: "self", "user".')

    def _get_default_system(self) -> str:
        today = datetime.now().strftime('%Y-%m-%d')
        return (f'You are a helpful AI assistant.\nKnowledge cutoff: {self.knowledge_cutoff}.'
                f'\nCurrent date: {today}.')

    def _swift_prepare_inputs(self, inputs: StdTemplateInputs):
        super()._swift_prepare_inputs(inputs)
        if not self.use_chat_template:
            return
        # `prefix` renders `{{SYSTEM}}` unconditionally, so the whole system block is materialized
        # here -- the jinja template emits it even when the conversation carries no system message.
        system = inputs.system
        if system is None:
            system = self._get_default_system()
        if not system.startswith('<|start|>'):
            inputs.system = f'<|start|>system<|message|>{system}{self._get_system_suffix()}<|eot|>'
        for message in inputs.messages:
            # The generation prompt is only `<|start|>assistant`; the recipient and the
            # `<|message|>` marker are generated by the model and thus belong to the response.
            if message['role'] == 'assistant' and isinstance(message['content'], str):
                if not message['content'].startswith(' to='):
                    message['content'] = ' to=user<|message|>' + message['content']

    def replace_tag(self, media_type: Literal['image', 'video', 'audio'], index: int,
                    inputs: StdTemplateInputs) -> List[Context]:
        assert media_type in {'image', 'video'}
        return ['<|patch|>'] if media_type == 'image' else ['<|video|>']

    def _encode(self, inputs: StdTemplateInputs) -> Dict[str, Any]:
        encoded = super()._encode(inputs)
        processor = self.processor
        input_ids = encoded['input_ids']
        labels = encoded['labels']
        loss_scale = encoded.get('loss_scale', None)
        for media_type in ['images', 'videos']:
            mm_data = getattr(inputs, media_type)
            if not mm_data:
                continue
            if media_type == 'images':
                media_inputs = processor.image_processor(images=mm_data, return_tensors='pt')
                media_token = self.image_token_id
                replace_token = processor.replace_image_token
            else:
                media_inputs = processor.video_processor(videos=mm_data, return_tensors='pt')
                media_token = self.video_token_id
                replace_token = processor.replace_video_token
            idx_list = findall(input_ids, media_token)

            # Delegate the expansion to the processor: it wraps the patches in
            # `<|image_start|>`/`<|image_end|>` and, for videos, interleaves per-frame timestamps
            # and separators. Reimplementing that here would silently drift from the reference.
            def _get_new_tokens(i):
                return self._tokenize(replace_token(media_inputs, i))

            input_ids, labels, loss_scale = self._extend_tokens(input_ids, labels, loss_scale, idx_list,
                                                                _get_new_tokens)
            # `video_metadata` only feeds the timestamps in the expansion above; it holds plain
            # python objects that the collator cannot batch and the model does not accept.
            media_inputs.pop('video_metadata', None)
            encoded.update(media_inputs)

        encoded['input_ids'] = input_ids
        encoded['labels'] = labels
        encoded['loss_scale'] = loss_scale
        return encoded


@dataclass
class MuseGlimmerTemplateMeta(TemplateMeta):
    prefix: Prompt = field(default_factory=lambda: ['<|begin_of_text|>{{SYSTEM}}'])
    prompt: Prompt = field(default_factory=lambda: ['<|start|>user<|message|>{{QUERY}}<|eot|><|start|>assistant'])
    chat_sep: Optional[Prompt] = field(default_factory=lambda: ['<|eot|>'])
    suffix: Prompt = field(default_factory=lambda: ['<|eot|>'])


register_template(MuseGlimmerTemplateMeta(MLLMTemplateType.muse_glimmer, template_cls=MuseGlimmerTemplate))
