### model
model: /nas_train/app.e0016372/models/lmms-lab/LLaVA-OneVision-1.5-4B

### method
# debug: true
stage: sft
tuner_type: full
freeze_vit: true
freeze_llm: true
freeze_aligner: false

### optimize
attn_impl: flash_attn
use_liger_kernel: false
vit_gradient_checkpointing: false
gradient_checkpointing_kwargs: {"use_reentrant": false}

### dataset
cached_dataset:
  - /nas_user/app.e0016372/datasets/Open-Bee/Bee-Training-Data-Stage1/cache/train
packing: true
max_length: 8192
max_pixels: 2560000
dataloader_num_workers: 8
dataloader_persistent_workers: true
# split_dataset_ratio: 0.01
# load_from_cache_file: true

### output
output_dir: /nas_train/app.e0016372/train/LLaVA-OneVision-1.5-4B/openbee
logging_steps: 10
save_strategy: steps
save_steps: 100
save_total_limit: 1
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
weight_decay: 0.01
warmup_ratio: 0.03
learning_rate: 1e-3
num_train_epochs: 1.0
lr_scheduler_type: cosine
torch_dtype: bfloat16
deepspeed: zero2

### plugins
external_plugins:
  - randy/plugins/dataset.py
