### model
model: /nas_train/app.e0016372/train/sft/full/LLaVA-OneVision-1.5-32B/v1-20260513-210256/last
model_type: llava_onevision1_5

### method
# debug: true
stage: sft
tuner_type: full
lora_rank: 16
lora_alpha: 32
freeze_vit: false
freeze_llm: false
freeze_aligner: false

### optimize
attn_impl: flash_attn
use_liger_kernel: false
vit_gradient_checkpointing: true
gradient_checkpointing_kwargs: {"use_reentrant": false}

### dataset
cached_dataset:
  - /nas_user/app.e0016372/datasets/LLaVA-OneVision-1.5-Instruct-Data/cache/train
packing: true
max_length: 16384
max_pixels: 2560000
dataloader_num_workers: 8
dataloader_persistent_workers: true
# split_dataset_ratio: 0.01
# load_from_cache_file: true

### output
output_dir: /nas_train/app.e0016372/train/sft/full/LLaVA-OneVision-1.5-32B
logging_steps: 10
save_strategy: steps
save_steps: 1000
save_total_limit: 2
report_to: tensorboard
create_checkpoint_symlink: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
weight_decay: 0.0
warmup_ratio: 0.03
learning_rate: 1e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs: {"min_lr": 1e-6}
torch_dtype: bfloat16
deepspeed: zero3

### plugins
external_plugins:
  - randy/plugins/model.py
  - randy/plugins/dataset.py
  - randy/plugins/template.py
