### model
model: /nas_train/app.e0016372/models/openbmb/MiniCPM-V-4.6-4B

### method
# debug: true
stage: sft
tuner_type: full
lora_rank: 16
lora_alpha: 32
freeze_vit: true
freeze_llm: true
freeze_aligner: false

### optimize
attn_impl: flash_attn
use_liger_kernel: false
gradient_checkpointing: false
gradient_checkpointing_kwargs: {"use_reentrant": false}

### dataset
dataset: llava_pretrain_558k
packing: false
max_length: 4096
# max_pixels: 2560000
dataloader_num_workers: 8
dataloader_persistent_workers: true
# split_dataset_ratio: 0.01
load_from_cache_file: true

### output
output_dir: /nas_train/app.e0016372/train/sft/full/MiniCPM-V-4.6-4B
logging_steps: 10
save_strategy: steps
save_steps: 200
save_total_limit: 2
report_to: tensorboard

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
weight_decay: 0.0
warmup_ratio: 0.03
learning_rate: 1e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs: {"min_lr": 1e-6}
torch_dtype: bfloat16
deepspeed: zero2

### plugins
external_plugins:
  - randy/plugins/model.py
  - randy/plugins/dataset.py
  - randy/plugins/template.py
