PYTHONPATH=. torchrun examples/pytorch/stable_diffusion/finetune_stable_diffusion.py \
    --model 'AI-ModelScope/stable-diffusion-v2-1' \
    --model_revision 'v1.0.1' \
    --prompt "a dog" \
    --work_dir './tmp/lora_diffusion' \
    --train_dataset_name 'buptwq/lora-stable-diffusion-finetune' \
    --max_epochs 200 \
    --lora_rank 16 \
    --lora_alpha 24 \
    --save_ckpt_strategy 'by_epoch' \
    --logging_interval 1 \
    --train.dataloader.workers_per_gpu 0 \
    --evaluation.dataloader.workers_per_gpu 0 \
    --train.optimizer.lr 1e-4 \
    --sample_nums 10 \
    --num_inference_steps 30 \
    --use_model_config true
