rlhf_type: grpo

model: Qwen/Qwen2.5-0.5B-Instruct
dataset: AI-MO/NuminaMath-TIR#100
reward_funcs: [accuracy]
overlong_filter: false
dataset_num_proc: 2
split_dataset_ratio: 0

micro_batch_size: 2
global_batch_size: 16
num_generations: 4
steps_per_generation: 1
logging_steps: 1
seed: 42
max_length: 1024
max_completion_length: 512
padding_free: false
cross_entropy_loss_fusion: true
gradient_accumulation_fusion: false
lr: 5e-5
lr_warmup_fraction: 0.0
min_lr: 5e-5
attention_backend: flash
temperature: 1.0
beta: 0
epsilon: 0.2
epsilon_high: 0.28
loss_type: grpo
advantage_estimator: grpo
importance_sampling_level: token
log_rollout_offpolicy_metrics: true
train_iters: 5

use_vllm: true

colocate_groups: [[train, rollout]]
offload_model: true
offload_optimizer: true
sleep_level: 1

train:
  gpus: 2
  tuner_type: lora
  lora_rank: 8
  lora_alpha: 32
  tensor_model_parallel_size: 1
  output_dir: megatron_output/t5_ray_grpo

rollout:
  gpus: 2
  vllm_tensor_parallel_size: 1
  vllm_gpu_memory_utilization: 0.4
  vllm_max_model_len: 2048
